### ISSUE TITLE
Missing License!

### ISSUE THREAD

**Issue by sscarduzio** [Tonel/landing-page-template-nextjs#2]
Would be amazing if you would choose a liberal license, otherwise we can't use this. Thank you for your work!

**Comment by Tonel** [comment]
@sscarduzio Sorry, what license are you referring to?

**Comment by sscarduzio** [comment]
This repository does not have a license file. Is this open source? Can I reuse this code as a starting point of derived work? No license means no explicit permission to reuse, unfortunately.

I suggest using MIT license for this, in line with similar project.

**Comment by Tonel** [comment]
@sscarduzio ok, thanks! Now, I get it. Yeah, you are free to reuse it however you want!
